# Literature

The effects of winter storms are extensive. Each winter storm event brings costs assumed in travel delay and weather-related crashes. As a winter storm begins, there is typically a reduction in pavement friction due to ice and snow compacted on the roadway. Based on drivers’ perception of the roadway conditions, most users will decrease their travel speeds during winter storm events (Holik et al. 2015). The FHWA has found that average arterial speeds decline by 30 to 40 percent for snowy and slushy pavements. On freeways, speeds can be reduced by 3 to 13 percent in light snow and by 5 to 40 percent in heavy snow (FHWA 2020b). In Baltimore, Minneapolis, St. Paul, and Seattle, speeds were shown to reduce by 5 to 16 percent on average due to snow (Hranac et al. 2006). In addition to decreased speeds, volume and capacity reductions have also been found, as shown in Table 1. 

**Table 1. Traffic Flow Reductions on Freeways due to Winter Weather (FHWA 2020a)**

|Weather Conditions|Freeway Traffic Flow Reductions|
|------------------|-------------------------------|
| |Average Speed (%)|Free Flow Speed (%)|Volume (%)|Capacity (%)|
|Light Rain/Snow|3 - 13|2 - 13|5 - 10|4 - 11|
|Heavy Snow|5 - 40|5 - 64|30 - 44|12 - 27|
|Low Visibility|10 - 12|N/A|N/A|12|

Traffic volumes are also affected during winter storms. When traffic volumes are decreased during a storm, there is a correlation to the impacts on traffic speeds. When there are fewer vehicles on the road, it is more likely that traffic speeds will be closer to normal, even during winter storms. This, however, depends on the severity of the storm. Traffic volumes are reduced at different times of day, with PM peak volumes being impacted less when compared to AM peak volumes. There are fewer drivers out during the AM peak. There is also a large difference in volume during off-peak hours, suggesting drivers will alter their travel if possible (Hanbali 1992). 

With the reduction of traffic speeds during winter weather, travel delay is increased. To the user, traffic congestion can be costly, estimated at 78 billion in user costs per year (Schrank and Lomax 2007). About 15 percent of congestion is due to weather events, leading to almost $12 billion in user costs per year resulting from the weather (Cambridge Systematics Inc. and Texas Transportation Institute 2004). Winter weather affects travel time, speed, and costs for both individuals and businesses.

In addition to speeds, safety is a great concern during winter weather conditions. The FHWA reported that each year in the United States, 24 percent of weather-related crashes happen on snowy, slushy, or icy pavement. Of those crashes, 15 percent occurred during snowfall or sleet, which result in over 1,300 people that are killed and over 116,800 that are injured (FHWA 2020b). These statistics are what drive DOTs to spend millions of dollars on winter maintenance each year.

Using 10 years of data that resulted from weather-related conditions, the FHWA compiled annual average weather-related crash statistics. Both weather and pavement conditions were analyzed with the results shown in Table 2. Based on averages from the 10-year span, each year, 5,891,000 vehicle crashes occur throughout the United States. Of those crashes, 21 percent (1,235,000) are weather-related. Of the weather-related crashes that occurred, 18 percent (222,300) happened in snow or sleet conditions (FHWA 2020a).

Table 2

A variety of studies have been conducted to see when winter weather-related crashes are likely to occur. One study examined the relationship between winter weather precipitation and severity of crashes for 13 cities in the United States from 1996 to 2010 by analyzing crash and weather data. The locations for the study were chosen due to the frequency and type of winter precipitation they experience but did not include Utah. The results of the research showed that injury collision risk increased by 13 percent during winter precipitation compared to a control period. The strongest predictors for crashes were precipitation intensity, time of day, and order of precipitation. Crashes occurred more often during intense precipitation, during the afternoon and evening parts of the day, and during the first three precipitation events of a winter season (Black and Mote 2015). 