# Applications

Some _significant_ applications are demonstrated in this chapter.


The datasets were correlated together to find results. Traffic speed data were used to compare normal versus snow days to determine the effect of snow storms on traffic speeds. Storm severity was then compared to weather data to determine the effects of levels of severity on traffic speeds.

A similar analysis was done for crash data. Crash data were compared to weather data to analyze the frequency of crashes per storm severity level. The crash data were also compared with traffic data. The comparison of the three datasets showed the interaction between storm severity, traffic speed, and crash rates. 


##Goal: Compare speed and storm data

Compare normal v weather days with a t-test to find statistical significant differences
**Show chart of this

Correlate dates and times for routes & RWIS sites

Run avg speed per storm severity overall
***Bar chart or table

See variance on routes with speeds at different storm severity
Maybe do another t-test here?
**Table to show one segment and how speed changes over storm severity