# Conclusion and Acknowledgements

**Conclusion**

As the population within the state continues to grow, UDOT has continued to place great importance on timely maintenance during these winter storms. Its winter maintenance goal each year is to minimize fatalities and maintain network flow. The data were collected from a variety of sources for this study to analyze storm severity and traffic speeds for arterials in the Salt Lake Valley. The winter weather data was collected from UDOT’s Road Weather Information System (RWIS) locations and storm severity was found from UDOT’s storm severity measure. Traffic speeds were gathered and the speeds during winter storms were compared and effects were determined. The analysis shows that the difference between traffic speeds on snowy days versus normal days is minimal, but that the heavier snowfall has more impact on traffic speeds. As snow severity increases, traffic speeds decrease. These findings show the trends on the selected routes in Salt Lake during the 2019-2020 winter.

**Acknowledgment**

The author thanks the Utah Department of Transportation for support and funding for this research. S. Lau downloaded and analyzed the data and wrote the text, M. Shoaf downloaded and helped analyze the data, D. Eggett helped perform statistical analysis on the data, and G. Schultz supervised the work and assisted as needed. A huge thanks to G. Macfarlane for his coaching and constant encouragment of learning R. The author actually knows something now about R!