--- 
title: "Winter Storm Impacts on Traffic Speed and Safety in Salt Lake City"
author: "Samantha K. Lau, E.I.T; 
         Mason Shoaf, E.I.T;
         Dennis L. Eggett, Ph.D;
         Grant G. Schultz, Ph.D, P.E., PTOE"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "This is a term project for CE EN 594R."
---

# Abstract

The objective of this research was to analyze winter weather impacts on traffic speed and safety for arterial roads in Salt Lake City, Utah. This analysis included the correlation of storm severity data, traffic speeds, and crash data. The data were gathered for the 2019-2020 winter season for each snow storm. Storm severity was determined during 15-minute intervals for the duration of the overall storm. For weather days and days with no weather, the difference of speeds was determined and contrasted to speed limits. Storm severity, traffic speed, and crash data were compared and analyzed per storm, day of the week, and time of day to find statistical trends. The results indicated if a storm is low severity or medium severity, traffic speeds are typically faster than days with no weather and faster than the posted speed limits, due to the lower volumes of vehicles on the road. This resulted in no effect on crashes. However, on high severity storms, speeds decreased, and crashes increased. During the PM peak hour, traffic speeds decreased below normal and crashes increased. The AM peak period did not see the same results, as traffic volumes are typically decreased in the morning during a snow storm. These research findings show the correlation of winter weather severity, traffic speeds, and crash data for arterials in the Salt Lake City area. The findings can be used to access impacts of Utah’s current winter weather maintenance programs on arterial roads.